### ISSUE TITLE
Display Msg and Hire me only if the link is provided

### ISSUE THREAD

**Issue by sreevyshnavi02** [danishzayan/StudentsShowcase#14]
The *message* button is linked to redirect to the same website again when msgURL is left blank in the profileData. It would be better if the button is displayed only if there is a valid URL in the msgURL field. In that way, the button wouldn't be dummy.

**Comment by danishzayan** [comment]
> The _message_ button is linked to redirect to the same website again when msgURL is left blank in the profileData. It would be better if the button is displayed only if there is a valid URL in the msgURL field. In that way, the button wouldn't be dummy.

@sreevyshnavi02 now you can work on this issue.
