### ISSUE TITLE
Add Scroll to top button.

### ISSUE THREAD

**Issue by danishzayan** [danishzayan/StudentsShowcase#4]
Add a button in bottom right corner when user click on the button then it should smooth scroll to the top .

**Comment by DakshaPatel22** [comment]
I want to resolve your issue...

**Comment by AdarshP1133** [comment]
I can resolve the issues.

**Comment by danishzayan** [comment]
> I want to resolve your issue...

You @DakshaPatel22 now you can work on this issue..

**Comment by danishzayan** [comment]
> I can resolve the issues.

@AdarshP1133 add a search 🔍 button in navbar when I click search button then I will be visible and search should be show.

**Comment by prashant226** [comment]
assign this to me

**Comment by danishzayan** [comment]
> assign this to me

Done
