### ISSUE TITLE
Separate data file from script.js file.

### ISSUE THREAD

**Issue by danishzayan** [danishzayan/StudentsShowcase#7]
From script.js file do replace `usersProfile` data in `profileData.js`

**Comment by prashant226** [comment]
please assign to me

**Comment by danishzayan** [comment]
> please assign to me

Now you can start.

**Comment by Baburao-sanivada** [comment]
Can i Work on This?

**Comment by danishzayan** [comment]
> Can i Work on This?

yes of course.

**Comment by Baburao-sanivada** [comment]
Created a pull Request Can you Check it

**Comment by danishzayan** [comment]
> Created a pull Request Can you Check it
fix it after that i will merge your code

not working, you can check it. https://github.com/danishzayan/StudentsShowcase/pull/8#issuecomment-1741983268

**Comment by prashant226** [comment]
created pull request please check

**Comment by danishzayan** [comment]
> created pull request please check

@prashant226 bro already done this task.. ✅

**Comment by Gurnav224** [comment]
can I work on this issue
assign to me

**Comment by danishzayan** [comment]
> can I work on this issue assign to me

Task done ✅
